export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST';
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS';
<<<<<<< HEAD
export const PRODUCT_LIST_FAIL = 'PRODCUT_LIST_FAIL';


export const PRODUCT_DETAILS_REQUEST = 'PRODUCT_DETAILS_REQUEST';
export const PRODUCT_DETAILS_SUCCESS = 'PRODUCT_DETAILS_SUCCESS';
export const PRODUCT_DETAILS_FAIL = 'PRODCUT_DETAILS_FAIL';
=======
export const PRODUCT_LIST_FAIL = 'PRODCUT_LIST_FAIL';
>>>>>>> 00bcf477599fafbfa2b5cb93e004f4de3cf5941d
